version: '3'

services:
  db:
    image: postgres
    ports:
    - "5431:5432"
  web:
    build: .
    env_file:
      - .env
    command: bash -c "pwd && printenv & python3 manage.py runserver 0.0.0.0:8000"
    volumes:
    - ./:/web/template/api
    ports:
    - "8000:8000"
    depends_on:
    - db
