"""
Django production settings for rhythm project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from .settings import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [os.environ.get('API_DOMAIN', None)]

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'rhythm'),
        'USER': os.environ.get('DATABASE_USER', 'rhythm_user'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'rhythm_password'),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DATABASE_PORT', '5432'),
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FROM = 'info@localhost'

MEDIA_ROOT = os.path.join(BASE_DIR, os.environ.get('MEDIA_PATH', '../media/'))

CORS_ORIGIN_WHITELIST = (
    os.environ.get('UI_DOMAIN', None),
    os.environ.get('LOCAL_TESTER', None)
)

# Production Validations

assert all(ALLOWED_HOSTS), 'add allowed hosts'

assert all(CORS_ORIGIN_WHITELIST), 'add remote hosts which will use current server'
